return {
  {
    "xiyaowong/transparent.nvim",
    opts = {
      background_colour = "#555555",
      -- transparent background for toggleterm
      groups = { -- table: default groups
        "Normal",
        "NormalNC",
        "NormalFloat",
        "Comment",
        "Constant",
        "Special",
        "Identifier",
        "Statement",
        "PreProc",
        "Type",
        "Underlined",
        "Todo",
        "String",
        "Function",
        "Conditional",
        "Repeat",
        "Operator",
        "Structure",
        "LineNr",
        "NonText",
        "SignColumn",
        "CursorLineNr",
        "EndOfBuffer",
      },
      extra_groups = {},
      exclude_groups = {},
    },
  },
}
